### ISSUE TITLE
Exception when trying to run a risk session

### ISSUE THREAD

**Issue by manolodd** [RISCOSS/riscoss-platform-core#14]
See screenshot.

Entity -> Activae
Risk model -> FBK License Risk Configuration 2
RISCOSS Instance -> http://riscossplatform.ow2.org/riscoss/wiki/wiki1/login/Main/WebHome

I started the risk configuration session while the fosology data collector was still running (no data available, then).
![captura](https://cloud.githubusercontent.com/assets/5189679/6125842/b76806f0-b11a-11e4-9334-8bb8eb2d7707.png)

**Comment by cjdelisle** [comment]
Make sure you're using the right risk configuration, fbk added some models/configs which are not working on that platform. The right one is called `OW2RiskConfiguration`

**Comment by manolodd** [comment]
Ok, so.. should these non-valid models be there? This is the public instance!!

**Comment by albertosiena** [comment]
The models are valid.
The platform should support them.
We already filed an issue on github some weeks ago.

**Comment by manolodd** [comment]
Ok, using OW2RiskConfiguration it works!! but as I already don't have raw data (data collector is still runing), the analysis is useless. Maybe it should be a good idea avoid starting a risk session if there are not available data yet (suggestion).

**Comment by manolodd** [comment]
Yes Alberto, I wanted to say that these models are not working on the platform, as Caleb said. Sorry.

**Comment by cjdelisle** [comment]
I think this was caused by spaces in filenames, please reopen if *exactly* this error shows up again, there are other issues with people uploading incompatible models which are a different matter.
