### ISSUE TITLE
need standard names for data points which are collected from data collectors

### ISSUE THREAD

**Issue by cjdelisle** [RISCOSS/riscoss-platform-core#7]
We need to have standardization of data point names so that the collectors and models will be reusable.

**Comment by rbenjacob** [comment]
RBJ 22/1
The requirements were documented and discussed as follows:

**Input fields and names:**
Each data element (input fields from data sources) must be mapped to risk driver (inputs to the risk analysis)

Risk drivers become the input nodes in the Bayesian network

The mapping and of data elements to risk drivers and naming of risk drivers is done during setup time

**Regarding OW2:**
The above was performed on Cedric's initial Excel - input data elements were mapped to risk drivers which were than were used to create the 3 indicator BNs (activeness, quality and license)

**Performing and analysis:**
Data collector should be able to identify which data element is the source for which risk driver

Data collector/RISCOSS platform should be able to create appropriate distribution of each **input data element**, based on setup definition of groups, and pass to the risk analysis tool **risk drivers' distributions**

**ALL** risk drivers are mandatory. There can't be a situation where data is missing for some

When data is missing for certain data element (e.g. wasn't part of the recent data collection), use the values from previous data collection. Default values are the initial values used for setup, thus enduring that the analysis won't fail

Adopters (users) should be notified of missing values and use of non-current values

**Comment by cjdelisle** [comment]
We're currently prefixing the names with using the type of entity `OSSComp|UseCase` (filled in by the platform), the data collector (eg: `github`) and then the data point, separated by `:`. I think this resolves the original concern.
